{% set name = "revive" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mgechev/revive/archive/v{{ version }}.tar.gz
  sha256: 1624844ed9a3e33fab2f1af6485a3894be2e6050c8f06ecfc83fc236cbc09192

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/mgechev/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast, configurable, extensible, flexible, and beautiful linter for Go
  dev_url: https://github.com/mgechev/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
