schema_version: 1

context:
  version: "1.17.1"

package:
  name: revive
  version: ${{ version }}

source:
  url: https://github.com/mgechev/revive/archive/v${{ version }}.tar.gz
  sha256: 52782382c491aacbf2074df09cbd2e5105c3c0c4fac44b3e273f616068a51d75

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - revive --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast, configurable, extensible, flexible, and beautiful linter for Go
  homepage: https://github.com/mgechev/revive
  repository: https://github.com/mgechev/revive

extra:
  recipe-maintainers:
    - danielnachun
