schema_version: 1

context:
  version: "1.17.0"

package:
  name: revive
  version: ${{ version }}

source:
  url: https://github.com/mgechev/revive/archive/v${{ version }}.tar.gz
  sha256: 8e9034bf3f268ec9ff3edbceb6cf8bad8947383733c5e24ca2ae2fbffe8d0ef3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - revive --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast, configurable, extensible, flexible, and beautiful linter for Go
  homepage: https://github.com/mgechev/revive
  repository: https://github.com/mgechev/revive

extra:
  recipe-maintainers:
    - danielnachun
