schema_version: 1

context:
  version: "1.15.0"

package:
  name: revive
  version: ${{ version }}

source:
  url: https://github.com/mgechev/revive/archive/v${{ version }}.tar.gz
  sha256: c3bec8123b8b1bf6c11fb82ed7638241c8910104725a4ff22b3c26b62ae83d5d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - revive --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Fast, configurable, extensible, flexible, and beautiful linter for Go
  homepage: https://github.com/mgechev/revive
  repository: https://github.com/mgechev/revive

extra:
  recipe-maintainers:
    - danielnachun
